# Generated by Django 5.2.7 on 2025-10-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['created']},
        ),
    ]
