# Generated by Django 5.2.7 on 2025-12-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_paticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
